name: Reusable steps (AKA composite action)
description: Demonstrate how to use reusable steps in a workflow

runs:
  using: 'composite'
  steps:
    - name: Step Name1
      id: process-step
      shell: bash 
      run: |
        echo "Reusable steps - 1"
    - name: Step Name2
      shell: bash 
      run: |
        echo "$(hostname)"